const div = document.getElementById('div-id')
console.log(div.children[0])
console.log(div.childNodes[0])
// div.removeChild(div.childNodes[0])
// div.removeChild(div.childNodes[1])
// console.log(div)